### ISSUE TITLE
Unable to build including tests

### ISSUE THREAD

**Issue by W4RH4WK** [allscale/allscale_runtime#15] opened 2017-10-05 09:09 UTC
I am currently unable to build the AllScale runtime with tests enabled.

The full logfile can be found [here](https://gist.github.com/W4RH4WK/135b0b592829cf489820f8310298400c)

AllScale Runtime: https://github.com/W4RH4WK/allscale_runtime/tree/fix-cpufreq \
HPX: 35428360f0cbde7f9ff697008649dbc75c0a67e2\
API: c81015dc5339a9af834c5d760fe3ca18636bbf5c

Configuration:

    $ cmake ~/allscale_runtime/ \
        -DCPUFREQ_ROOT=/insieme-libs/cpufrequtils-008 \
        -DHPX_DIR=/insieme-dev/alex/allscale_build/hpx-prefix/src/hpx-build/lib/cmake/HPX \
        -DALLSCALE_API_DIR=$HOME/allscale/api \
        -DALLSCALE_WITH_TESTS=ON

Let me know if you require more information about my current environment.

**Comment by hendrx** [comment] 2017-10-05 10:35
Had to temporarily comment out the tests  and examples related to these errors, should build for now.
work in progress !

**Comment by W4RH4WK** [comment] 2017-10-05 11:01
I just rebased the CPUFREQ fix and tried out the new version. Still with `-DALLSCALE_WITH_TESTS` set, it does not compile. I extended the gist with the new (quite similar) log output (`log2.txt`).

Does the build succeed with this setup (API / HPX version) and tests enabled on your end?

Edit: I completely wiped the build directory before running `cmake` and `make`.

**Comment by hendrx** [comment] 2017-10-12 10:35
@W4RH4WK :  

You are building with commit 35428360f0cbde7f9ff697008649dbc75c0a67e2 which is from 06/09/2017.
Issue was reopened 05/10/2017. Commit you used is almost a month old, did you try with newest HPX commit?

I just build current Master without errors, with tests, using
 
HPX: 8ecf8197f9fc9d1cd45a7f9ee61a7be07ba26f46
ALLSCALE_API: f4763c7d55385cbd8931c80dea9213189759020d


Suggestion:
If errors show up, try using respective HPX commit at times, instead of using code which is almost a month outdated.

**Comment by destructor64** [comment] 2017-10-13 07:20
The issue is still there using the latest commits of the runtime and HPX respectively, like it can be seen in this gist: https://gist.github.com/peterz-dps/25831cf20b0ac3ba0420c851ff9c11ec

> Suggestion:
If errors show up, try using respective HPX commit at times, instead of using code which is almost a month outdated.

So my counter-suggestion would be:
Could you have a look at this again? There still seems to be some code path to the serialization stuff.

> I just build current Master without errors, with tests, using

Yeah, you were able to build without errors 13 minutes after you commited 0c667deefdb73eef88925ea325f16f249e2aabaf closing issue #16 which finally enabled to build _some_ stuff, after the build has been broken for a week now...

**Comment by sithhell** [comment] 2017-10-13 08:12
Current master works fine for me.
The error you are running into is from a insieme test. Which is unrelated to the problem reported initially.
When calling the backend compiler from the allscale compiler, you should set the "ALLSCALE_WITH_HPX" define. If that's omitted, the serialization wrapper for HPX inside the AllScale API isn't enabled, which leads exactly to those problems.

**Closed as completed by sithhell** 2017-10-13 08:12 UTC

**Comment by W4RH4WK** [comment] 2017-10-13 09:48
Thank you for the help. I am now able to build the AllScale runtime with the current version of HPX and the AllScale API -- and tests enabled.

API: 6da705b698bc37397306d585473aa9116b4237a4
HPX: c043c77664091bf62035cff02188a8a4b07d908f

- - -

@hendrx: Can you please clarify how I can identify a *respective HPX commit at times*. Does the AllScale runtime somehow tell me which HPX commit should be used? Or do you guarantee that the AllScale runtime will always build with most recent (with respect to the runtime commit) commit of HPX.

How does your CI system check the build status? Does it simply checkout the most recent version of HPX, AllScale API and runtime? Or is there some kind of staging involved?

**Comment by W4RH4WK** [comment] 2017-10-19 08:44
@hendrx: We agreed on adding HPX as Git submodule to the AllScale Runtime.
